### ISSUE TITLE
Add timing information to pipeline diagrams

### ISSUE THREAD

**Issue by schmmd** [allenai/pipeline#1]
@kwhumphreys requested timing information to be added to the pipeline diagrams.  This seems like an excellent addition--although it might not be easy to implement for the Spark components.

@rodneykinney are you OK if I try and implement this on Monday?

**Comment by rodneykinney** [comment]
Timing information sounds like a great idea.  It's complicated by the fact
that a step might be re-using cached data instead of running.  That might
be useful information to highlight in the diagram, come to think of it.

You might consider making this change on my refactoring branch:
https://github.com/allenai/pipeline/tree/io-refactor One change I've
already made on this branch is to output the diagram even for failed runs,
highlighting the steps that didn't complete.

rk

**Comment by schmmd** [comment]
Added https://github.com/allenai/pipeline/pull/2 (manually merged).
